spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=product_schema
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update