spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db?currentSchema=product_schema
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 300_000 #5 minutes
      maximumPoolSize: 10
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update